spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MSSQLServer

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  sql:
    init:
      data-locations: classpath:db/data/*.sql
      schema-locations: classpath:db/schema/*.sql
      mode: always
  config:
    activate:
      on-profile: test

logging:
  level:
    org.hibernate.sql: error
    org.hibernate.type.descriptor.sql: error

